"""empty message

Revision ID: fd4857a29cdb
Revises: 2aaaaa2db515
Create Date: 2024-01-15 16:06:36.660601

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fd4857a29cdb'
down_revision = '2aaaaa2db515'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cms_house', sa.Column('community', sa.String(length=200), nullable=True))
    op.add_column('cms_house', sa.Column('deposit', sa.Integer(), nullable=True))
    op.add_column('cms_house', sa.Column('mobile', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cms_house', 'mobile')
    op.drop_column('cms_house', 'deposit')
    op.drop_column('cms_house', 'community')
    # ### end Alembic commands ###
